---
- hosts: default
  become: true
  vars:
    - virtualenv: "/opt/citoengine"
    - mysql_root_pass: "root"
    - citoengine_user: "citoengine"
    - citoengine_pass: "citoengine"
    - citoengine_email: "oscara.lopez@softtek.com"
    - citoengine_tz: "America/Mexico_City"
  roles:
    - { role: citoengine }
